<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.12.4 on linux)" generated="2024-06-26T03:01:25.560688" rpa="false" schemaversion="5">
<suite id="s1" name="Jpetstore" source="/tmp/rfswarmagent/scripts/jpetstore.robot">
<test id="s1-t1" name="Jpetstore 01" line="16">
<kw name="Open Store">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2024-06-26T03:01:25.691671" level="INFO">Creating Session using : alias=jpetstore, url=http://192.168.13.82:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>${SessAlias}</arg>
<arg>${StorePage}</arg>
<arg>verify=False</arg>
<arg>disable_warnings=1</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2024-06-26T03:01:25.691287" elapsed="0.000642"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2024-06-26T03:02:46.270876" level="FAIL">ConnectionError: HTTPConnectionPool(host='192.168.13.82', port=8080): Max retries exceeded with url: /jpetstore/actions/Catalog.action (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x72a162518290&gt;: Failed to establish a new connection: [Errno 113] No route to host'))</msg>
<var>${resp}</var>
<arg>${SessAlias}</arg>
<arg>/jpetstore/actions/Catalog.action</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2024-06-26T03:01:25.692221" elapsed="80.582489">ConnectionError: HTTPConnectionPool(host='192.168.13.82', port=8080): Max retries exceeded with url: /jpetstore/actions/Catalog.action (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x72a162518290&gt;: Failed to establish a new connection: [Errno 113] No route to host'))</status>
</kw>
<kw name="Get Resources">
<arg>${resp}</arg>
<status status="NOT RUN" start="2024-06-26T03:02:46.275470" elapsed="0.000034"/>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>${resp.cookies}[JSESSIONID]</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.275975" elapsed="0.000027"/>
</kw>
<kw name="Set Test Variable" owner="BuiltIn">
<arg>$JSESSIONID</arg>
<arg>${resp.cookies}[JSESSIONID]</arg>
<doc>Makes a variable available everywhere within the scope of the current test.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.276220" elapsed="0.000025"/>
</kw>
<doc>Opens jpetstore</doc>
<status status="FAIL" start="2024-06-26T03:01:25.690537" elapsed="80.585958">ConnectionError: HTTPConnectionPool(host='192.168.13.82', port=8080): Max retries exceeded with url: /jpetstore/actions/Catalog.action (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x72a162518290&gt;: Failed to establish a new connection: [Errno 113] No route to host'))</status>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>16</arg>
<arg>Sleep added by RFSwarm</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.279415" elapsed="0.000036"/>
</kw>
<kw name="Nav Fish" source_name="Nav ${Animal}">
<var>${products}</var>
<doc>Navigate to catagory page</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.279754" elapsed="0.000029"/>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>30</arg>
<arg>Sleep added by RFSwarm</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.281020" elapsed="0.000027"/>
</kw>
<kw name="Evaluate" owner="BuiltIn">
<var>${product}</var>
<arg>random.choice(${products})</arg>
<arg>modules=random</arg>
<doc>Evaluates the given expression in Python and returns the result.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.281268" elapsed="0.000024"/>
</kw>
<kw name="Nav Product">
<arg>${product}</arg>
<doc>Navigate to product page</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.281664" elapsed="0.000026"/>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>32</arg>
<arg>Sleep added by RFSwarm</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.282947" elapsed="0.000038"/>
</kw>
<kw name="Delete All Sessions" owner="RequestsLibrary">
<doc>Removes all the session objects</doc>
<status status="NOT RUN" start="2024-06-26T03:02:46.283214" elapsed="0.000025"/>
</kw>
<status status="FAIL" start="2024-06-26T03:01:25.689969" elapsed="80.593548">ConnectionError: HTTPConnectionPool(host='192.168.13.82', port=8080): Max retries exceeded with url: /jpetstore/actions/Catalog.action (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x72a162518290&gt;: Failed to establish a new connection: [Errno 113] No route to host'))</status>
</test>
<meta name="RFS_AGENTNAME">agent-000</meta>
<meta name="RFS_AGENTVERSION">1.3.1</meta>
<meta name="RFS_DEBUGLEVEL">2</meta>
<meta name="RFS_EXCLUDELIBRARIES">RequestsLibrary,BuiltIn,String,OperatingSystem,perftest</meta>
<meta name="RFS_INDEX">1</meta>
<meta name="RFS_INJECTSLEEP">True</meta>
<meta name="RFS_ITERATION">1</meta>
<meta name="RFS_ROBOT">29</meta>
<meta name="RFS_SLEEPMAXIMUM">45</meta>
<meta name="RFS_SLEEPMINIMUM">15</meta>
<meta name="RFS_SWARMMANAGER">http://hp-elite-desk-800-g3:8138/</meta>
<status status="FAIL" start="2024-06-26T03:01:25.652100" elapsed="80.632360"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Jpetstore">Jpetstore</stat>
</suite>
</statistics>
<errors>
<msg time="2024-06-26T03:02:46.275760" level="ERROR">Calling method 'end_keyword' of listener '/tmp/rfswarmagent/scripts/RFSListener3.py' failed: KeyError: 'doc'</msg>
</errors>
</robot>
